version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PGID
      - PUID
      - TZ
    command: --interval 720 --cleanup --rolling-restart
    restart: always

  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    hostname: nzbget
    ports:
      - "6789:6789"
    volumes:
      - ${CONFIG}/nzbget:/config
      - ${DOWNLOAD}:/downloads/
    environment:
      - PGID
      - PUID
      - TZ
    restart: always

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    ports:
      - "8989:8989"
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${DOWNLOAD}:/downloads
      - ${MEDIA}/TV:/tv
    environment:
      - PGID
      - PUID
      - TZ
    restart: always

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    hostname: radarr
    ports:
      - "7878:7878"
    volumes:
      - ${CONFIG}/radarr:/config
      - ${DOWNLOAD}:/downloads
      - ${MEDIA}/Movies:/movies
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID
      - PUID
      - TZ
    restart: always

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    hostname: plex
    #network_mode: "host"
    ports:
      - "32401:32400/tcp"
    volumes:
      - ${CONFIG}/plex:/config
      - ${MEDIA}/TV:/media/tv
      - ${MEDIA}/Movies:/media/movies
      - ${MEDIA}/Music:/media/music
      - ${MEDIA}/Audiobooks:/media/audiobooks
      - ${MEDIA}/YouTube:/media/youtube
      - ${CACHE}:/transcode
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID
      - PUID
      - TZ
      - VERSION=latest
    restart: always

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    #network_mode: "host"
    ports:
      - 33010:8096
    volumes:
      - ${CONFIG}/jelly:/config
      - ${MEDIA}/TV:/media/tv
      - ${MEDIA}/Movies:/media/movies
      - ${MEDIA}/Music:/media/music
      - ${MEDIA}/Audiobooks:/media/audiobooks
      - ${MEDIA}/YouTube:/media/youtube
      - ${CACHE}:/cache
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID
      - PUID
      - TZ
    restart: always

  plexpy:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    hostname: tautulli
    ports:
      - "8181:8181"
    volumes:
      - ${CONFIG}/plexpy:/config
      - ${CONFIG}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    environment:
      - PGID
      - PUID
      - TZ
    restart: always

  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    hostname: ombi
    ports:
      - "27016:3579"
    volumes:
      - ${CONFIG}/ombi:/config
    environment:
      - PGID
      - PUID
      - TZ
    restart: always
