version: '3'

services:
  watchtower:
    image: containrrr/watchtower 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    hostname: nzbget
    ports:
      - "6789:6789"
    volumes:
      - ${CONFIG}/nzbget:/config
      - ${DOWNLOAD}:/downloads/
    environment:
      - PGID
      - PUID
      - TZ
    restart: always

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    ports:
      - "8989:8989"
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${DOWNLOAD}:/downloads
      - ${MEDIA}/TV:/tv
    environment:
      - PGID
      - PUID
      - TZ
    restart: always

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    hostname: radarr
    ports:
      - "7878:7878"
    volumes:
      - ${CONFIG}/radarr:/config
      - ${DOWNLOAD}:/downloads
      - ${MEDIA}/Movies:/movies
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID
      - PUID
      - TZ
    restart: always

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    hostname: plex
    #network_mode: "host"
    ports:
      - "32400:32400/tcp"
    volumes:
      - ${CONFIG}/plex:/config
      - ${MEDIA}/TV:/media/tv
      - ${MEDIA}/Movies:/media/movies
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGID
      - PUID
      - TZ
      - VERSION=latest
    restart: always

  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${CONFIG}/overseer:/config
    ports:
      - 5055:5055
    restart: unless-stopped 
