services:
  service_1:
    image: <dummy>/service_1:latest
    container_name: service_1
    hostname: service_1
    ports:
      - "6789:6789"
    volumes:
      - ${CONFIG}/service_1:/config
      - ${DOWNLOAD}:/downloads/
    environment:
      - PGID
      - PUID
      - TZ
    restart: on-failure