version: '3'

services:
  monitoring_portainer:
    hostname: monitoring_portainer
    container_name: monitoring_portainer
    image: portainer/portainer
    ports:
      - "4020:9000"
    environment:
      - TZ
      - PUID
      - PGID
    volumes:
      - ${DOCKERSOCK}:/var/run/docker.sock
      - ${STORAGE}/portainer_data:/data
    command: -H unix:///var/run/docker.sock

  monitoring_netdata:
    hostname: monitoring_netdata
    container_name: monitoring_netdata
    image: titpetric/netdata
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    ports:
      - "19999:19999"
    environment:
      - TZ
      - PUID
      - PGID
    volumes:
      - ${STORAGE}/netdata:/etc/netdata
      - ${PROC}:/host/proc:ro
      - ${SYS}:/host/sys:ro
      - ${DOCKERSOCK}:/var/run/docker.sock

  monitoring_caddy:
    container_name: monitoring_caddy
    hostname: monitoring_caddy
    image: stefanprodan/caddy
    restart: unless-stopped
    environment:
      - TZ
      - PUID
      - PGID
    ports:
      - "880:80"
      - "4443:443"