version: '3'

services:
  amqp_watchtower:
    image: v2tec/watchtower:latest
    command: --cleanup --label-enable --schedule="0 2 * * *"
    container_name: amqp_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TIMEZONE}:/etc/timezone:ro
      - ${LOCALTIME}:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: on-failure

  amqp_rabbitmq:
    image: rabbitmq:3-management
    container_name: amqp_rabbitmq
    hostname: amqp_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - PGID
      - PUID
      - TZ
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_VHOST
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: on-failure
