version: '3'
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    hostname: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./config:/config
    environment:
      - PGID
      - PUID
      - TZ
    restart: on-failure
