apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: juiceshop
  name: juiceshop
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: juiceshop
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: juiceshop
    spec:
      containers:
      - image: bkimminich/juice-shop
        imagePullPolicy: ""
        name: juiceshop
        ports:
        - containerPort: 3000
        resources: {}
      hostname: juiceshop
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
