version: '3'

services:
  mqtt_mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt_mosquitto
    hostname: mqtt_mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/:/mosquitto/data
      - ./config/:/mosquitto/log
    environment:
      - PGID
      - PUID
      - TZ
    restart: on-failure
