version: '3'
services:
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    hostname: transmission
    ports:
      - "9091:9091"
      - "8888:8888"
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 188.172.219.43
      - 188.172.192.19
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment: 
      - OPENVPN_PROVIDER
      - OPENVPN_USERNAME
      - OPENVPN_PASSWORD
      - OPENVPN_CONFIG
    # - OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60"
      - LOCAL_NETWORK=192.168.1.0/24
      - PGID
      - PUID
    volumes:
      - ${BLACKHOLE}:/data
      - ${LOCALTIME}:/etc/localtime:ro
    restart: always