version: '3'

services:
  wireguard:
    image: jordanpotter/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    volumes:
      - ${CONFIG}/mullvad.conf:/etc/wireguard/mullvad.conf
      - ${LOCALTIME}:/etc/localtime:ro
    restart: unless-stopped
  rtorrent:
    build:
      context: https://github.com/skandix/alpine-rtorrent.git
      args:
        - UGID=${RTORRENT_UID}
    image: alpine-rtorrent:local
    container_name: rtorrent
    depends_on:
      - "wireguard"
    network_mode: service:wireguard
    volumes:
      - ${CONFIG}/session:/home/rtorrent/rtorrent/.session
      - ${DOWNLOAD}/download/:/home/rtorrent/rtorrent/download
      - ${DOWNLOAD}/watch/:/home/rtorrent/rtorrent/watch
    restart: unless-stopped
  # For debugging purpose
  # curl:
  #   image: appropriate/curl
  #   container_name: curl
  #   command: http://httpbin.org/ip
  #   depends_on:
  #     - "wireguard"
  #   network_mode: service:wireguard
  #   restart: unless-stopped
