version: '3'

services:
  calibre:
    image: linuxserver/calibre-web
    container_name: calibre
    hostname: calibre
    ports:
      - "8083:8083"
    volumes:
      - ${CONFIG}/:/config
      - ${BOOKS}/:/books
    environment:
    - PGID
    - PUID
    - TZ
    restart: on-failure