version: '3'
services:
  deluge:
    image: binhex/arch-delugevpn
    container_name: deluge
    hostname: deluge
    ports:
      - "8112:8112"
      - "8118:8118"
      - "58846:58846"
      - "58946:58496"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_ENABLED
      - VPN_USER
      - VPN_PASS
      - VPN_PROV
      - STRICT_PORT_FORWARD
      - ENABLE_PRIVOXY
      - LAN_NETWORK
      - NAME_SERVERS
      - DEBUG
      - PGID
      - PUID
    volumes:
      - ./config:/config
      - ${DOWNLOAD}:/data/
      - ${LOCALTIME}:/etc/localtime:ro
    restart: always